version: 2.1 
 
orbs:
  win: circleci/python@2.0.3
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - checkout     
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run: echo "Starting... "; python3 duino.py
